### ISSUE TITLE
 Feedback on some issues

### ISSUE THREAD

**Issue by Lonely233233** [nv4d1k/live-stream-forwarder#1]
Douyu live streaming sometimes gets stuck.Can other live broadcast sources be added?

**Comment by nv4d1k** [comment]
Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.

**Comment by Lonely233233** [comment]
> Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.

https://github.com/youshandefeiyang/LiveRedirect/tree/main/Golang

There are multiple stream connection projects here. See if it helps.

**Comment by Lonely233233** [comment]
> Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.

Here "bilibili" can choose other stream connections

**Comment by nv4d1k** [comment]
> > Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.
> 
> Here "bilibili" can choose other stream connections

bilibili can get 1080p by v1 api now

**Comment by nv4d1k** [comment]
> > Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.
> 
> https://github.com/youshandefeiyang/LiveRedirect/tree/main/Golang
> 
> There are multiple stream connection projects here. See if it helps.

You may have misunderstood me. This project does not provide p2p multi-streaming, but only provides multi-format. For lsf, multi-format is not the optimal solution.

**Comment by Lonely233233** [comment]
> > > Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.
> > 
> > 
> > https://github.com/youshandefeiyang/LiveRedirect/tree/main/Golang
> > There are multiple stream connection projects here. See if it helps.
> 
> You may have misunderstood me. This project does not provide p2p multi-streaming, but only provides multi-format. For lsf, multi-format is not the optimal solution.


Can Douyin be changed to use FLV? m3u8 is not as smooth as flv

**Comment by nv4d1k** [comment]
> > > > Douyu Live uses Tencent’s x-p2p solution. Currently, lsf does not adopt a multi-stream p2p mode, but a single-stream p2p mode. Therefore, when the default p2p node provided by Douyu goes offline, the video will be interrupted. Currently the player can solve this problem by stopping and restarting. As for the multi-stream p2p model, I am currently still studying how to assemble the data of multiple streams. There is no public documentation, so it will take some time.
> > > 
> > > 
> > > https://github.com/youshandefeiyang/LiveRedirect/tree/main/Golang
> > > There are multiple stream connection projects here. See if it helps.
> > 
> > 
> > You may have misunderstood me. This project does not provide p2p multi-streaming, but only provides multi-format. For lsf, multi-format is not the optimal solution.
> 
> Can Douyin be changed to use FLV? m3u8 is not as smooth as flv

HLS can use Apple TV to cast the screen, so this program will return the HLS stream first. After v0.0.8, support using "http://x.x.x.x:x/douyin/xxxx?format=flv" to obtain FLV format streams.
