### ISSUE TITLE
Douyin does not default to the highest quality of 60 FPS

### ISSUE THREAD

**Issue by Lonely233233** [nv4d1k/live-stream-forwarder#3]
![image](https://github.com/nv4d1k/live-stream-forwarder/assets/106970209/a2e1a762-37c5-4915-9c4e-cddcb7a1b59c)
Opening is not the default highest quality
![image](https://github.com/nv4d1k/live-stream-forwarder/assets/106970209/ca6f1bb1-a29d-4000-816c-94915ba561c8)
Source grabbed via F12 has 60FPS

**Comment by nv4d1k** [comment]
made origin stream prefer
